export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const GET_SITES = "GET_SITES";
export const GET_SITES_SUCCESS = "GET_SITES_SUCCESS";
export const ADD_SITE_SUCCESS = "ADD_SITE_SUCCESS";
export const UPDATE_SITE_SUCCESS = "UPDATE_SITE_SUCCESS";
export const DELETE_SITE_OPTIMISTIC = "DELETE_SITE_OPTIMISTIC";
